sudo: false
language: ruby
bundler_args: --without beaker
before_install:
  - gem update bundler
matrix:
  fast_finish: true
  include:
  - rvm: 2.1.9
    env: PUPPET_VERSION="~> 3.7"
  - rvm: 2.1.9
    env: PUPPET_VERSION="~> 4.0"
  - rvm: 2.2.6
    env: PUPPET_VERSION="~> 3.7"
  - rvm: 2.2.6
    env: PUPPET_VERSION="~> 4.0"
  - rvm: 2.4.0
    env: PUPPET_VERSION="~> 3.7"
  - rvm: 2.4.0
    env: PUPPET_VERSION="~> 4.0"
notifications:
  email: false
