sudo: false
language: ruby
bundler_args: --without beaker
before_install:
  - gem update bundler
rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.4
env:
  - PUPPET_GEM_VERSION="~> 3.7"
  - PUPPET_GEM_VERSION="~> 4.0"
matrix:
  fast_finish: true
notifications:
  email: false
